#include "opcode.h"

#define ERROR		isa__error

static const InstructionPtr opcodes[] = {
	isa_nop,       /* 0x00 */
	ERROR,         /* 0x01 */
	ERROR,         /* 0x02 */
	ERROR,         /* 0x03 */
	ERROR,         /* 0x04 */
	isa_load,      /* 0x05 */
	isa_store,     /* 0x06 */
	ERROR,         /* 0x07 */
	ERROR,         /* 0x08 */
	ERROR,         /* 0x09 */
	isa_in,        /* 0x0A */
	isa_out,       /* 0x0B */
	ERROR,         /* 0x0C */
	ERROR,         /* 0x0D */
	ERROR,         /* 0x0E */
	ERROR,         /* 0x0F */
	isa_push,      /* 0x10 */
	ERROR,         /* 0x11 */
	ERROR,         /* 0x12 */
	isa_mul,       /* 0x13 */
	ERROR,         /* 0x14 */
	isa_div,       /* 0x15 */
	ERROR,         /* 0x16 */
	isa_jmpf,      /* 0x17 */
	isa_jmpb,      /* 0x18 */
	isa_jz,        /* 0x19 */
	isa_jl,        /* 0x1A */
	ERROR,         /* 0x1B */
	ERROR,         /* 0x1C */
	ERROR,         /* 0x1D */
	ERROR,         /* 0x1E */
	ERROR,         /* 0x1F */
	isa_call,      /* 0x20 */
	ERROR,         /* 0x21 */
	isa_ret,       /* 0x22 */
	ERROR,         /* 0x23 */
	ERROR,         /* 0x24 */
	ERROR,         /* 0x25 */
	ERROR,         /* 0x26 */
	ERROR,         /* 0x27 */
	ERROR,         /* 0x28 */
	ERROR,         /* 0x29 */
	ERROR,         /* 0x2A */
	ERROR,         /* 0x2B */
	ERROR,         /* 0x2C */
	ERROR,         /* 0x2D */
	ERROR,         /* 0x2E */
	ERROR,         /* 0x2F */
	isa_alloc,     /* 0x30 */
	isa_free,      /* 0x31 */
	ERROR,         /* 0x32 */
	ERROR,         /* 0x33 */
	ERROR,         /* 0x34 */
	ERROR,         /* 0x35 */
	ERROR,         /* 0x36 */
	ERROR,         /* 0x37 */
	ERROR,         /* 0x38 */
	ERROR,         /* 0x39 */
	ERROR,         /* 0x3A */
	ERROR,         /* 0x3B */
	ERROR,         /* 0x3C */
	ERROR,         /* 0x3D */
	ERROR,         /* 0x3E */
	ERROR,         /* 0x3F */
	ERROR,         /* 0x40 */
	ERROR,         /* 0x41 */
	ERROR,         /* 0x42 */
	ERROR,         /* 0x43 */
	ERROR,         /* 0x44 */
	ERROR,         /* 0x45 */
	ERROR,         /* 0x46 */
	ERROR,         /* 0x47 */
	ERROR,         /* 0x48 */
	ERROR,         /* 0x49 */
	ERROR,         /* 0x4A */
	ERROR,         /* 0x4B */
	ERROR,         /* 0x4C */
	ERROR,         /* 0x4D */
	ERROR,         /* 0x4E */
	ERROR,         /* 0x4F */
	ERROR,         /* 0x50 */
	ERROR,         /* 0x51 */
	ERROR,         /* 0x52 */
	ERROR,         /* 0x53 */
	ERROR,         /* 0x54 */
	ERROR,         /* 0x55 */
	ERROR,         /* 0x56 */
	isa_pop,       /* 0x57 */
	ERROR,         /* 0x58 */
	isa_dup,       /* 0x59 */
	ERROR,         /* 0x5A */
	ERROR,         /* 0x5B */
	ERROR,         /* 0x5C */
	ERROR,         /* 0x5D */
	ERROR,         /* 0x5E */
	isa_swap,      /* 0x5F */
	isa_add,       /* 0x60 */
	ERROR,         /* 0x61 */
	ERROR,         /* 0x62 */
	ERROR,         /* 0x63 */
	isa_sub,       /* 0x64 */
	ERROR,         /* 0x65 */
	ERROR,         /* 0x66 */
	ERROR,         /* 0x67 */
	ERROR,         /* 0x68 */
	ERROR,         /* 0x69 */
	ERROR,         /* 0x6A */
	ERROR,         /* 0x6B */
	ERROR,         /* 0x6C */
	ERROR,         /* 0x6D */
	ERROR,         /* 0x6E */
	ERROR,         /* 0x6F */
	ERROR,         /* 0x70 */
	ERROR,         /* 0x71 */
	ERROR,         /* 0x72 */
	ERROR,         /* 0x73 */
	ERROR,         /* 0x74 */
	ERROR,         /* 0x75 */
	ERROR,         /* 0x76 */
	ERROR,         /* 0x77 */
	ERROR,         /* 0x78 */
	ERROR,         /* 0x79 */
	ERROR,         /* 0x7A */
	ERROR,         /* 0x7B */
	ERROR,         /* 0x7C */
	ERROR,         /* 0x7D */
	isa_and,       /* 0x7E */
	ERROR,         /* 0x7F */
	isa_or,        /* 0x80 */
	ERROR,         /* 0x81 */
	ERROR,         /* 0x82 */
	ERROR,         /* 0x83 */
	ERROR,         /* 0x84 */
	ERROR,         /* 0x85 */
	ERROR,         /* 0x86 */
	ERROR,         /* 0x87 */
	ERROR,         /* 0x88 */
	ERROR,         /* 0x89 */
	ERROR,         /* 0x8A */
	ERROR,         /* 0x8B */
	ERROR,         /* 0x8C */
	ERROR,         /* 0x8D */
	ERROR,         /* 0x8E */
	ERROR,         /* 0x8F */
	ERROR,         /* 0x90 */
	ERROR,         /* 0x91 */
	ERROR,         /* 0x92 */
	ERROR,         /* 0x93 */
	ERROR,         /* 0x94 */
	ERROR,         /* 0x95 */
	ERROR,         /* 0x96 */
	ERROR,         /* 0x97 */
	ERROR,         /* 0x98 */
	ERROR,         /* 0x99 */
	ERROR,         /* 0x9A */
	ERROR,         /* 0x9B */
	ERROR,         /* 0x9C */
	ERROR,         /* 0x9D */
	ERROR,         /* 0x9E */
	ERROR,         /* 0x9F */
	ERROR,         /* 0xA0 */
	ERROR,         /* 0xA1 */
	ERROR,         /* 0xA2 */
	ERROR,         /* 0xA3 */
	ERROR,         /* 0xA4 */
	ERROR,         /* 0xA5 */
	ERROR,         /* 0xA6 */
	ERROR,         /* 0xA7 */
	ERROR,         /* 0xA8 */
	ERROR,         /* 0xA9 */
	ERROR,         /* 0xAA */
	ERROR,         /* 0xAB */
	ERROR,         /* 0xAC */
	ERROR,         /* 0xAD */
	ERROR,         /* 0xAE */
	ERROR,         /* 0xAF */
	ERROR,         /* 0xB0 */
	ERROR,         /* 0xB1 */
	ERROR,         /* 0xB2 */
	ERROR,         /* 0xB3 */
	ERROR,         /* 0xB4 */
	ERROR,         /* 0xB5 */
	ERROR,         /* 0xB6 */
	ERROR,         /* 0xB7 */
	ERROR,         /* 0xB8 */
	ERROR,         /* 0xB9 */
	ERROR,         /* 0xBA */
	ERROR,         /* 0xBB */
	ERROR,         /* 0xBC */
	ERROR,         /* 0xBD */
	ERROR,         /* 0xBE */
	ERROR,         /* 0xBF */
	ERROR,         /* 0xC0 */
	ERROR,         /* 0xC1 */
	ERROR,         /* 0xC2 */
	ERROR,         /* 0xC3 */
	ERROR,         /* 0xC4 */
	ERROR,         /* 0xC5 */
	ERROR,         /* 0xC6 */
	ERROR,         /* 0xC7 */
	ERROR,         /* 0xC8 */
	ERROR,         /* 0xC9 */
	ERROR,         /* 0xCA */
	ERROR,         /* 0xCB */
	ERROR,         /* 0xCC */
	ERROR,         /* 0xCD */
	ERROR,         /* 0xCE */
	ERROR,         /* 0xCF */
	ERROR,         /* 0xD0 */
	ERROR,         /* 0xD1 */
	ERROR,         /* 0xD2 */
	ERROR,         /* 0xD3 */
	ERROR,         /* 0xD4 */
	ERROR,         /* 0xD5 */
	ERROR,         /* 0xD6 */
	ERROR,         /* 0xD7 */
	ERROR,         /* 0xD8 */
	ERROR,         /* 0xD9 */
	ERROR,         /* 0xDA */
	ERROR,         /* 0xDB */
	ERROR,         /* 0xDC */
	ERROR,         /* 0xDD */
	ERROR,         /* 0xDE */
	ERROR,         /* 0xDF */
	ERROR,         /* 0xE0 */
	ERROR,         /* 0xE1 */
	ERROR,         /* 0xE2 */
	ERROR,         /* 0xE3 */
	ERROR,         /* 0xE4 */
	ERROR,         /* 0xE5 */
	ERROR,         /* 0xE6 */
	ERROR,         /* 0xE7 */
	ERROR,         /* 0xE8 */
	ERROR,         /* 0xE9 */
	ERROR,         /* 0xEA */
	ERROR,         /* 0xEB */
	ERROR,         /* 0xEC */
	ERROR,         /* 0xED */
	ERROR,         /* 0xEE */
	ERROR,         /* 0xEF */
	ERROR,         /* 0xF0 */
	ERROR,         /* 0xF1 */
	ERROR,         /* 0xF2 */
	ERROR,         /* 0xF3 */
	ERROR,         /* 0xF4 */
	ERROR,         /* 0xF5 */
	ERROR,         /* 0xF6 */
	ERROR,         /* 0xF7 */
	ERROR,         /* 0xF8 */
	ERROR,         /* 0xF9 */
	ERROR,         /* 0xFA */
	ERROR,         /* 0xFB */
	ERROR,         /* 0xFC */
	ERROR,         /* 0xFD */
	isa_exit,      /* 0xFE */
	ERROR,         /* 0xFF */
};

InstructionPtr instr_by_code(unsigned char code)
{
	return opcodes[code];
}

